[build]
target = [
  "aarch64-apple-darwin",
  "aarch64-apple-ios",
  "aarch64-linux-android",
  "aarch64-unknown-linux-gnu",
  "x86_64-apple-darwin",
  "x86_64-apple-ios",
  "x86_64-pc-windows-gnu",
  "x86_64-unknown-linux-gnu",
]

